import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "introduction",
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      items: ["installation", "configuration"],
    },
    {
      type: "category",
      label: "Integration",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: ["github"],
    },
    {
      type: "category",
      label: "Core Features",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: ["features", "plugins", "themes"],
    },
    {
      type: "category",
      label: "Core concepts",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [
        "plugin-architecture",
        "markdown-processing",
        "nodes",
        "transformers",
        "content-synchronization",
      ],
    },
    {
      type: "category",
      label: "Advanced Topics",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [
        "transformer-tutorial",
        "custom-git-providers",
      ],
    },
  ],
  // API documentation sidebar
  apiSidebar: [
    {
      type: "autogenerated",
      dirName: "api",
    },
  ],
  // Community documentation sidebar
  communitySidebar: [
    {
      type: "autogenerated",
      dirName: "community",
    },
  ],
};

export default sidebars;
