import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "introduction",
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      items: ["installation", "authentication"],
    },
    {
      type: "category",
      label: "Advanced Guides",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: ["github-tutorial", "transformer-tutorial"],
    },
    {
      type: "category",
      label: "References TODO Vérifier ordre",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [
        "content-synchronization",
        "markdown-processing",
        "nodes",
        "transformers",
        "plugins",
        "provided-api",
      ],
    },
    "further-improvements",
  ],
  apiSidebar: [
    {
      type: "autogenerated",
      dirName: "api",
    },
  ],
  communitySidebar: [
    {
      type: "autogenerated",
      dirName: "community",
    },
  ],
};

export default sidebars;
